config/routes.rb
Rails.application.routes.draw do
  	root 'sign_motions#index'

end

app/models/sign_motion.rb
class SignMotion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sign_motions_controller.rb
class SignMotionsController < ApplicationController
  before_action :set_sign_motion, only: [:show, :edit, :update, :destroy]

  # GET /sign_motions
  # GET /sign_motions.json
  def index
    @sign_motions = SignMotion.all
  end

  # GET /sign_motions/1
  # GET /sign_motions/1.json
  def show
  end

  # GET /sign_motions/new
  def new
    @sign_motion = SignMotion.new
  end

  # GET /sign_motions/1/edit
  def edit
  end

  # POST /sign_motions
  # POST /sign_motions.json
  def create
    @sign_motion = SignMotion.new(sign_motion_params)

    respond_to do |format|
      if @sign_motion.save
        format.html { redirect_to @sign_motion, notice: 'Sign motion was successfully created.' }
        format.json { render :show, status: :created, location: @sign_motion }
      else
        format.html { render :new }
        format.json { render json: @sign_motion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_motions/1
  # PATCH/PUT /sign_motions/1.json
  def update
    respond_to do |format|
      if @sign_motion.update(sign_motion_params)
        format.html { redirect_to @sign_motion, notice: 'Sign motion was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_motion }
      else
        format.html { render :edit }
        format.json { render json: @sign_motion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_motions/1
  # DELETE /sign_motions/1.json
  def destroy
    @sign_motion.destroy
    respond_to do |format|
      format.html { redirect_to sign_motions_url, notice: 'Sign motion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_motion
      @sign_motion = SignMotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_motion_params
      params.fetch(:sign_motion, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sign_motions_helper.rb
module SignMotionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SignLanguage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sign_motions/_form.html.erb
<%= form_for(@sign_motion) do |f| %>
  <% if @sign_motion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_motion.errors.count, "error") %> prohibited this sign_motion from being saved:</h2>

      <ul>
      <% @sign_motion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sign_motions/edit.html.erb
<h1>Editing Sign Motion</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_motion %> |
<%= link_to 'Back', sign_motions_path %>

app/views/sign_motions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App for sign language study</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"> Ведуться технічні роботи.</th>
    </tr>
     <tr>
      <th colspan="3"> </th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<br>

app/views/sign_motions/new.html.erb
<h1>New Sign Motion</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_motions_path %>

app/views/sign_motions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sign_motion_path(@sign_motion) %> |
<%= link_to 'Back', sign_motions_path %>